name: Lint Node.js

on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - "src-tauri/**"
      - "README.md"

concurrency:
  group: ci-js-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: true

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Set up Node.js LTS v16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn

      - name: Run lint step
        run: yarn lint